- hosts: webservers
  tasks:
    - yum:
        name: "httpd"
    - service:
        name: "httpd"
        state: "restarted"
        enabled: "yes"
- hosts: dbservers
  tasks:
    - yum:
        name: "mariadb-server"
    - service:
        name: "mariadb"
        state: "restarted"
        enabled: "yes"
